name: 'textlint'

on:
  pull_request:
    branches:
      - 00_docs_jp_textllint
    paths:
      - 'docs/ja/**/*.md'
      - 'docs/ja/*.md'

jobs:
  linter:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/ja
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup nodejs'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 'Setup reviewdog'
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: 'Install node dependencies'
        run: npm ci

      - name: 'textlint & reviewdog'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (github.event_name == 'pull_request') }}
        run: |
          DIFF_FILES=`git diff --name-status origin/00_docs_jp_textllint --diff-filter=MA | grep -E 'docs/ja/.*/*.md| docs/ja/*.md'| cut -f2| sed -e 's/docs\/ja\//\.\//g'`
          if [ -z "${DIFF_FILES}" ]; then exit 0; fi
          npx textlint -f checkstyle $(echo ${DIFF_FILES}) | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review --fail-on-error=false -filter-mode=added
