name: run-textlint
on:
  pull_request_target:
    types: [ opened, synchronize ]
    paths: [ '**/*.md' ]
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/ja
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages via packages.json
        run: npm install
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Filter changed files in src directory
        id: filter-files
        run: |
          echo "##[set-output name=filtered_files;]$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^docs/ja' | tr '\n' ' ')"
      - name: Run textlint (avoiding error)
        run: |
          for file in ${{ steps.filter-files.outputs.filtered_files }}; do
            echo $file
            npx textlint $file -o ./.textlint.log | true
          done
        shell: bash {0}
      - name: Report if textlint finds problems
        run: |
          if [ -e ./.textlint.log ]; then
            # create body file
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            cat ./.textlint.log | sed "s/${pwd_esc}/### :warning: ./g" >> ./.body.txt
            # pr comment
            gh pr comment --body-file ./.body.txt "${URL}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
